### ISSUE TITLE
Set App id and other parameter

### ISSUE THREAD

**Issue by alikianinejad** [chabokpush/chabok-client-rn#1]
i have configure my project based on [Instruction](https://github.com/chabokpush/chabok-client-rn#getting-started---ios) for react-native ios project but in basic usage i can't find how to pass parameters app_id, username, password and ... 
'

**Comment by Husseinhj** [comment]
Update the readme file.

```
const options = {
  "appId": "APP_ID",
  "apiKey": "API_KEY",
  "username": "USERNAME",
  "password": "PASSWORD",
  "isDev": true
};

this.chabok = new chabok.AdpPushClient();

this.chabok.initializeApp('APP_Name', options , (response) => {
  console.log('app initialized', response)
});

....
```
