### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by Mr-Hqq** [chabokpush/chabok-client-rn#14]
Hi!
When i send my push too my app return connectionStatus Instead message  from ChabokMessageReceived event.

**Comment by Mr-Hqq** [comment]
Please Answer.

**Comment by amir-yaghoobi** [comment]
Please provide more informations, like in `android` or `ios` device, and your push payload

**Comment by Mr-Hqq** [comment]
Its android emulator.
and the same data and notification to another app has been sent.
and this app don't received notification.

**Comment by behrad** [comment]
> When i send my push too my app return connectionStatus Instead message from ChabokMessageReceived event.

For any team to be able to support and handle questions, there's a need to be provided more information.
So please provide a sample code snippet of your usage, or related exception/error message, or more info generally about whats happening.
Your question is so not clear.

**Comment by Mr-Hqq** [comment]
This is my usage code


let chabokEmitter = null
const SIZE = 40;
class Home extends Component {

    constructor(props) {
        super(props);
        this.state = {
            isLoading: false,
            activeTab: 'inOrder',
            newWork: false,
            message: {}
        };
        this.growAnimated = new Animated.Value(0);
        this.socket = SocketIOClient('ws://bimocenter.com:8888');
        this.socket.on('message', this.onReceivedMessage);
        chabokEmitter = new NativeEventEmitter(NativeModules.AdpPushClient);
    }
    componentWillMount() {
        const {auth, work, history} = this.props;
        if (auth.status === true) {
            this.setState({activeTab: 'inOrder'})
        } else {
            this.setState({activeTab: 'outOfOrder'})
        }
        const options = {
            "appId": "doajibuv/1095716090078",
            "apiKey": "2c5af9a7e5ed85dfff623a920029d796c066edb5",
            "username": "zonuzkuaci",
            "password": "rivuluwuda",
            "isDev": true
        };
        const USER = auth.id.toString() + "_repairman";
        this.chabok = new chabok.AdpPushClient();
        this.chabok.initializeApp("chabokdemos", options, (response) => {
            console.log('app initialized', response)
        });
        this.chabok.register(USER, []);
        work.isWork ? history.push('/newRequest'): '';
    }
    componentDidMount() {
        chabokEmitter.addListener(
            'connectionStatus',
            (status) => {
                console.log('connectionStatus', status)
            }
        );
        chabokEmitter.addListener(
            'ChabokMessageReceived',
            (message) => {
                console.log(message)
                this.setState({newWork: true, message: message});
            }
        );
    }

this is image of whats happend when i send push:
![image](https://user-images.githubusercontent.com/19619231/45470700-fd96a400-b743-11e8-9885-5ac0065a5ac9.png)

actually when i send push has to received to this callBack:

        chabokEmitter.addListener(
            'ChabokMessageReceived',
            (message) => {
                console.log(message)
                this.setState({newWork: true, message: message});
            }
        );

but below callBack has action:

        chabokEmitter.addListener(
            'connectionStatus',
            (status) => {
                console.log('connectionStatus', status)
            }
        );

**Comment by behrad** [comment]
1. Please use correct code formatting tags for your code! [javascript formatter]
2. Never put your account information inside GITHUB issues

I edited your issue.

Your logs shows that you are connected to chabok, but message never received! So this is not a connection issue, You are not receiving message.

Check your panel to see why your message is not delivered to that device.
