### ISSUE TITLE
console.log calls must be removed from production build

### ISSUE THREAD

**Issue by arastu** [chabokpush/chabok-client-rn#15]
console.log() statements are really handy tools for JavaScript development, but I think it must delete on the production build.
https://github.com/chabokpush/chabok-client-rn/blob/35c334fd0aea5410b83488ff4ede4ec5478ebb65/lib/modules/core/chabok.js#L15
If you remove console log expression you can remove constructor method too, because when you do not specify a constructor method a default constructor is used.

**Comment by amir-yaghoobi** [comment]
@arastu you are right about this, we will resolve this issue in next release
