### ISSUE TITLE
Cannot read property 'playServicesAvailability' of undefined

### ISSUE THREAD

**Issue by alikianinejad** [chabokpush/chabok-client-rn#2]
I have Ios Project with react native and try to config chabok on it 
but in this line 
`this.chabok = new chabok.AdpPushClient();`
i got this error: 
`Cannot read property 'playServicesAvailability' of undefined

<unknown>
    chabok.js:10:56
loadModuleImplementation
    require.js:214:4
guardedLoadModule
    require.js:148:11
_require
    require.js:132:2
<unknown>
    index.js:4
loadModuleImplementation
    require.js:214:4
guardedLoadModule
    require.js:148:11
_require
    require.js:132:2
<unknown>
    App.js:12
loadModuleImplementation
    require.js:214:4`

**Comment by alikianinejad** [comment]
nothing ?

**Comment by behrad** [comment]
We have configured react native bridge for iOS successfully in our projects.

Can you provide us more details about the chabok section of your code?

**Comment by amir-yaghoobi** [comment]
I think you forgot to do the [linking](https://github.com/chabokpush/chabok-client-rn#installation) part.
please run 
```
react-native link react-native-chabok
```
 this should solve the problem. otherwise please provide more information about steps you take to build the project from scratch.

**Comment by alikianinejad** [comment]
all done tnx
