### ISSUE TITLE
دریافت اطلاعات نوتیفیکیشن در هنگام کلیک یا باز کردن نوتیفیکیشن

### ISSUE THREAD

**Issue by miladrasooli** [chabokpush/chabok-client-rn#22]
با سلام ، من نوتیفیکیشن رو موقع بسته بودن برنامه دریافت میکنم ، اما وقتی برنامه بسته است و نوتیفیکیشن میاد و کاربر روش کلیک میکنه محتویات اون نوتیفیکیشن رو چطور توی برنامه بگیرم که به صفحه درست هدایتش کنم؟

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">محتویات اون نوتیفیکیشن رو چطور توی برنامه بگیرم</p>
</blockquote>
<p dir="rtl">فعلا در این نسخه از کتابخانه ریکت‌نیتو این امکان وجود نداره، شما می‌توانید با خواند بخش مستندات <a href="https://doc.chabokpush.com/android/notification-handling.html#%D8%AA%D9%86%D8%B8%DB%8C%D9%85-%D9%86%D9%85%D8%A7%DB%8C%D8%B4-%D9%88-%DA%A9%D9%84%DB%8C%DA%A9-%D8%B1%D9%88%DB%8C-%D8%A7%D8%B9%D9%84%D8%A7%D9%86">اندروید</a> و <a href="https://doc.chabokpush.com/ios/notification.html#%D8%B1%D9%88%DB%8C%D8%AF%D8%A7%D8%AF-%DA%A9%D9%84%DB%8C%DA%A9-%D8%A8%D8%B1-%D8%B1%D9%88%DB%8C-%D8%A7%D8%B9%D9%84%D8%A7%D9%86-%D8%A2%DB%8C%D8%A7%D9%88%D8%A7%D8%B3-%DB%B1%DB%B0-%D8%A8%D9%87-%D8%A8%D8%A7%D9%84%D8%A7">iOS</a> این موضوع را هندل کنید.</p>
<p dir="rtl">هنگامی که اپلیکیشن به چابک متصل شود پیام چابک را دریافت می‌کند که در <a href="https://doc.chabokpush.com/react-native-bridge/chabok-messaging.html#%D8%AF%D8%B1%DB%8C%D8%A7%D9%81%D8%AA-%D9%BE%DB%8C%D8%A7%D9%85">این متد</a> می‌توانید اطلاعات پیام را دریافت کنید.</p>
