### ISSUE TITLE
  sample project (starter) مشکل بیلد نشدن  

### ISSUE THREAD

**Issue by rpmsoft** [chabokpush/chabok-client-rn#27]
** BUILD FAILED **

The following commands produced analyzer issues:

	Analyze Base/RCTModuleMethod.mm
	Analyze Modules/RCTUIManager.m
(2 commands with analyzer issues)

The following build commands failed:
	PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock build/Build/Intermediates.noindex/chabokstarterrnbridge.build/Debug-iphonesimulator/chabokstarterrnbridge.build/Script-9D749B9559B2BC2313AC4E65.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/chabokstarterrnbridge.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/chabokstarterrnbridge.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">میشه لطفا یه پروژه استارت که با ورژن react-native 0.57.4 همخوانی داشته باشه برام بفرستید</p>
</blockquote>
<p dir="rtl">در Repository پروژه Starter روی <a href="https://github.com/chabokpush/chabok-starter-rn/tree/dev/rn57">برنچ rn57</a> نسخه ریکت‌نیتو 0.57.4 قرار داده شده و باید روی اندروید و iOS بدون مشکل اجرا شود.</p>
<p dir="rtl">مشکل شما فقط روی پلتفرم iOS می‌باشد؟</p>
<p dir="rtl">در صورت امکان گزارش خطای جدید را برای ما در این ایشو قرار دهید.</p>

**Comment by rpmsoft** [comment]
merci az shoma , moshkele android ok shod , vali ios in error ro baz ham mide






** BUILD FAILED **







The following commands produced analyzer issues:

	Analyze Base/RCTModuleMethod.mm

	Analyze Modules/RCTUIManager.m

	Analyze RCTNetInfo.m

(3 commands with analyzer issues)



The following build commands failed:

	PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock build/Build/Intermediates.noindex/chabokstarterrnbridge.build/Debug-iphonesimulator/chabokstarterrnbridge.build/Script-9D749B9559B2BC2313AC4E65.sh

(1 failure)



Installing build/Build/Products/Debug-iphonesimulator/chabokstarterrnbridge.app

An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):

Failed to install the requested application

The bundle identifier of the application could not be determined.

Ensure that the application's Info.plist contains a value for CFBundleIdentifier.

Print: Entry, ":CFBundleIdentifier", Does Not Exist



Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/chabokstarterrnbridge.app/Info.plist

Print: Entry, ":CFBundleIdentifier", Does Not Exist





Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/chabokstarterrnbridge.app/Info.plist

Print: Entry, ":CFBundleIdentifier", Does Not Exist



    at checkExecSyncError (child_process.js:600:11)

    at Object.execFileSync (child_process.js:618:13)

    at Promise.then (/Users/rpmsoft/Desktop/chabok-starter-rn-dev-rn57/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)

    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by rpmsoft** [comment]
salam mishe lotfan javab bedin , android ok hastesh ama ios bazam error dare 


 



** BUILD FAILED **


The following commands produced analyzer issues:

	Analyze Base/RCTModuleMethod.mm
	Analyze Modules/RCTUIManager.m
	Analyze RCTNetInfo.m
(3 commands with analyzer issues)

The following build commands failed:
	PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock build/Build/Intermediates.noindex/chabokstarterrnbridge.build/Debug-iphonesimulator/chabokstarterrnbridge.build/Script-9D749B9559B2BC2313AC4E65.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/chabokstarterrnbridge.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/chabokstarterrnbridge.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/chabokstarterrnbridge.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:600:11)
    at Object.execFileSync (child_process.js:618:13)
    at Promise.then (/Users/rpmsoft/Desktop/chabok-starter-rn-dev-rn57/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Husseinhj** [comment]
<p dir="rtl">لطفا پروژه iOS را با Xcode باز کنید و با فشردن کلید ⌘B اقدام به build پروژه کنید. در بخش show the Report navigator خطایی که به شما نشان میدهد را اینجا برای ما قرار دهید. </p>
<p dir="rtl"><img src="https://user-images.githubusercontent.com/27139702/48280970-70817a00-e46a-11e8-82a5-02d68ef670a5.png" alt="image"></p>

<p dir="rtl">خطای ذکر شده در ایشوهای <a href="https://github.com/facebook/react-native/issues/21303">21303</a>, <a href="https://github.com/facebook/react-native/issues/20596">20596</a>, <a href="https://github.com/facebook/react-native/issues/14423">14423</a>  در پروژه ریکت‌نیتو ذکر شده است. </p>

**Comment by Husseinhj** [comment]
@rpmsoft مشکل شما حل شده است؟

**Comment by rpmsoft** [comment]
نه متاسفانه  :(

**Comment by Husseinhj** [comment]
<p dir="rtl">همچنان روی بیلد نسخه iOS مشکل دارید؟</p>
<p dir="rtl">پروژه را با xCode بیلد کنید و خطای آن را برای ما در اینجا قرار دهید تا بتوانیم مشکل شما را حل کنیم</p>

**Comment by rpmsoft** [comment]
![123](https://user-images.githubusercontent.com/44743162/48397509-2aab0700-e733-11e8-8949-8e2a133ab449.png)


in error ha hast

**Comment by Husseinhj** [comment]
<p dir="rtl">لطفا وارد دایرکتوری ios بشید :</p>
<pre><code>cd ios</code></pre><p dir="rtl">بعد دستور زیر رو وارد کنید:</p>
<pre><code>pod update</code></pre><p dir="rtl">سپس مجددا پروژه را با ایکس کد بیلد کنید. </p>
<blockquote dir="rtl">
<p dir="rtl">نسخه xcode رو هم اینجا برای ما قرار بدید</p>
</blockquote>

**Comment by Husseinhj** [comment]
<p dir="rtl">مقدار bundle Identifier را به یک مقدار دلخواه تغییر دهید</p>
<p dir="rtl">دقت کنید که آخرین تغییرات برنچ dev/rn57 را pull کرده باشید.</p>
<p dir="rtl">در صورت حل نشدن خطا cocoapod <a href="https://stackoverflow.com/questions/21366549/errorthe-sandbox-is-not-in-sync-with-the-podfile-lock-after-installing-res/36647507#36647507">این بخش</a> از stackoverflow را مطالعه کنید.</p>

**Comment by rpmsoft** [comment]
xcode ro update kardam , va project new sakhtam , ok shod
