### ISSUE TITLE
Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by miladrasooli** [chabokpush/chabok-client-rn#38]
<p dir="rtl">سلام من بعد از اضافه کردن چابک به پروژه آی او اس با استفاده از Pods خطای</p>
<pre><code>Undefined symbols for architecture i386</code></pre><p dir="rtl">رو میگیرم</p>
<p dir="rtl">ورژن ری اکت نیتیو ۵۵.۳</p>
<p dir="rtl">ورژن اکس کد ۱۰</p>
<p dir="rtl">خطای کامل تر :</p>
<pre><code>Undefined symbols for architecture i386:
  &quot;_OBJC_CLASS_$_PushClientMessage&quot;, referenced from:
      objc-class-ref in AdpPushClient-43138263d9eba3284b2b573a6a5e7e33a2e55b25c9556bc9357af2574f31640f.o
  &quot;_OBJC_CLASS_$_PushClientManager&quot;, referenced from:
      objc-class-ref in AdpPushClient-43138263d9eba3284b2b573a6a5e7e33a2e55b25c9556bc9357af2574f31640f.o
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)</code></pre>

**Comment by Husseinhj** [comment]
این مشکل در نسخه [#1.18.1](https://github.com/chabokpush/chabok-client-ios/releases/tag/v1.18.1) حل شده است
