### ISSUE TITLE
سازگاری با نسخه 0.59

### ISSUE THREAD

**Issue by ahmadina** [chabokpush/chabok-client-rn#43]
وقت بخیر
آیا اس دی کی چابک با ری اکت نیتیو 0.59 سازگار است؟

رویه رو طبق داکیومنت جلو رفتم اما با خطای 
error: package android.support.v4.content does not exist
import android.support.v4.content.LocalBroadcastManager;
                                 ^
error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat

مواجه شدم. از کد نمونه ای که گذاشته بودید چندین بار بررسی کردم و دقیقا همه چیز یکسان بود.

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">آیا اس دی کی چابک با ری اکت نیتیو 0.59 سازگار است؟</p>
</blockquote>
<p dir="rtl">بله سازگار هست. </p>
<p dir="rtl">برای اینکه در نسخه 0.59 از چابک بتونین استفاده کنین از دستور زیر استفاده کنین:</p>
<pre><code>yarn add https://github.com/chabokpush/chabok-client-rn.git#dev</code></pre>

**Comment by ahmadina** [comment]
طبق چیزی که عرض کردید انجام دادم اما همچنان خطا بالا وجود دارد با نمونه کد نیز مقایسه شد یکسان بود همه چی. دلیل خاصی داره این خطا؟

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">طبق چیزی که عرض کردید انجام دادم اما همچنان خطا بالا وجود دارد با نمونه کد نیز مقایسه شد یکسان بود همه چی. دلیل خاصی داره این خطا؟</p>
</blockquote>
<p dir="rtl">امکانش هست نسخه gradle plugin و gradle  رو در اختیار ما قرار بدید؟</p>
<p dir="rtl">همچنین با حفظ مسائل امنیتی گریدل اپلیکیشن خودتون رو برای ما ارسال کنید تا نسخه com.android.support:appcompat و همچنین buildTools رو بررسی کنیم</p>

**Comment by ahmadina** [comment]
**build.gradle:**

classpath 'com.android.tools.build:gradle:3.3.0'

**app/build.gradle:**

compileSdkVersion = 28
buildToolsVersion = '28.0.3'

implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
implementation 'com.android.support:support-v4:27.0.3'

compile 'me.leolin:ShortcutBadger:1.1.22@aar'
compile 'com.adpdigital.push:chabok-lib:2.17.1'
compile "com.google.android.gms:play-services-gcm:15.0.1"
implementation 'com.android.installreferrer:installreferrer:1.0'

این اطلاعات کافیه؟

**Comment by ahmadina** [comment]
<p dir="rtl">مشکلی که هست به طور دقیق در فایل <code>AdpPushClientModule</code> این قسمت خطا داره</p>
<pre><code class="language-java">import android.support.v4.app.NotificationCompat;
import android.support.v4.content.LocalBroadcastManager;</code></pre>
<p dir="rtl">و پیدا نمیشه</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">باید نسخه‌های این دو dependency یکسان باشه:</p>
<pre><code>implementation &#39;com.android.support:appcompat-v7:28.+&#39;
implementation &#39;com.android.support:support-v7:28.+&#39;</code></pre>

<p dir="rtl">همچنین dependancyهای خودتون رو با نسخه گریدلی که دارین به implementation تغییر بدید:</p>
<pre><code>implementation &#39;me.leolin:ShortcutBadger:1.1.22@aar&#39;
implementation &#39;com.adpdigital.push:chabok-lib:2.17.1&#39;
implementation &#39;com.google.android.gms:play-services-gcm:16.0.0&#39;
implementation &#39;com.android.installreferrer:installreferrer:1.0&#39;</code></pre>

**Comment by ahmadina** [comment]
درباره 
implementation 'com.android.support:support-v7:28.+'
مطمئن هستید؟

چون توی داک https://developer.android.com/topic/libraries/support-library/packages#v4 نداره همچین چیزی؟ و نصبشم نمیکنه

**Comment by Husseinhj** [comment]
<p dir="rtl">شما از این dependency استفاده می‌کنین؟</p>
<p dir="rtl"><a href="https://github.com/chabokpush/chabok-starter-rn/blob/81c20a4b9b7e860fbb06dbc7f43e15351c343355/android/app/build.gradle#L140-L148">نمونه کد ریکت‌نیتو چابک</a></p>

**Comment by ahmadina** [comment]
بله دقیقا.
مشکل از یک فایل داخلی داخل لایبرریه. من احتمال میدم سیستم شما از قبل داره نصب به همین دلیل مشکلی پیش نمیاد روی ۵۹
import android.support.v4.app.NotificationCompat;
import android.support.v4.content.LocalBroadcastManager;
که این دو کلاس در androidx موجود هستن الان

**Comment by ahmadina** [comment]
مشکل حل شد. 
داخل فایل 
AdPushClientModule.java
لایبرری های اندروید ایکس را جایگزین دو فایل زیر کردم و خطا حل شد
import android.support.v4.app.NotificationCompat;
import android.support.v4.content.LocalBroadcastManager;
