### ISSUE TITLE
اپ هیچ عکس العملی نداره

### ISSUE THREAD

**Issue by Mr-Hqq** [chabokpush/chabok-client-rn#5]
سلام و خسته نباشید
من همه کار های گفته شد رو انجام دادم اما اپ هیچ عکس العملی نداره
نه کاربر اضافه میشه
و connectionStatus هم disconnected می زنه

**Comment by Mr-Hqq** [comment]
بله دقیقا به همین شکل نوشته شده کد
اما باز با این حال هیچ عکس العملی نداره
متد register هم یه بار فراخونی میشه
initialize انجام میشه
`app initialized Object {result: "success"}`
اما connectionStatus خروجی خوشایندی نمیده

**Comment by Husseinhj** [comment]
<div dir='rtl'>
اگر دقیقا این کد رو رفتین، باید کار کنه. 
</div>

<pre >
app initialized Object {result: "success"}
</pre>

<div dir='rtl'>
لاگ بالا به این معنی هست که <code>initilize</code> کرده. 

اگر وی‌پی‌ان دارید، بدون وی‌پی‌ان تست کنین.

لاگ‌های اپ رو اینجا برای ما بفرستید 
اگر پلتفرم<code>iOS</code> دارید با استفاده از <code>property</code> زیر لاگ‌ها برای شما فعال میشه اینطوری می‌تونیم بهتر به شما کمک کنیم. کد فوق رو توی کلاس <code>AppDelegate</code> قرار بدید

</div>
<pre>
PushClientManager.defaultManager.enableLog = YES;
</pre>

**Comment by Mr-Hqq** [comment]
نه فقط اندرویده
وی پی ان رو هم خاموش کردم اما باز disconnected میده

تو لاگ کت اندروید استودیو این ارور رو میده
لاگ : 

> 08-26 12:00:59.391 29073-29149/com.repairman E/com.adpdigital.push.AdpPushClient: Cannot save device, Reason: Internal Server Error
    org.apache.http.client.HttpResponseException: Internal Server Error
        at a.f.sendResponseMessage(SourceFile:440)
        at a.e.run(SourceFile:2078)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by Mr-Hqq** [comment]
مشکل حل شد.
مشکل از ورژن استفاده شده بود.ممنون
