### ISSUE TITLE
عدم دریافت مقدار data

### ISSUE THREAD

**Issue by amir-yaghoobi** [chabokpush/chabok-client-rn#6]
<div dir=rtl>
مقدار <code>data</code> به درستی <code>parse</code> نمی‌شود که باعث عدم دریافت آن می‌شود
</div>

**Comment by amir-yaghoobi** [comment]
<div dir=rtl>
خیلی ممنون، اگه امکانش براتون هست pull-request این راه حل رو بزنین.
</div>

**Comment by behrad** [comment]
Can you please create a PR for your solution @Mr-Hqq ?

**Comment by Mr-Hqq** [comment]
it's done for goodness.
if i'm wrong let me to know!

**Comment by amir-yaghoobi** [comment]
This issue fixed in this PR  #10 and will be available in next version.

I will close this issue since its resolved.
